export const orderRequest = ({
    address,
    nameCustomer,
    emailCustomer,
    phoneNumberCustomer,
    totalPrice = 0,
    deliveryFee = 0,
    orderStatus = 1,
    deliveryStatus = 1,
    deliveryMethod = 1,
    couponCode = "",
    rejectReason = "",
    listOrderDetails = [],
} = {}) => ({
    address,
    nameCustomer,
    emailCustomer,
    phoneNumberCustomer,
    totalPrice,
    deliveryFee,
    orderStatus,
    deliveryStatus,
    deliveryMethod,
    couponCode,
    rejectReason,
    listOrderDetails,
});